[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "metaicvi"
authors = [{name = "Sasha Petrenko", email = "sap625@mst.edu"}]
dynamic = ["version", "description"]
